### ISSUE TITLE
[Forge] "Mixin apply failed" crash on startup if Axes are Weapons are present

### ISSUE THREAD

**Issue by pinkygrocket** [Jusey1/SaljuQuill#1]
[latest.log](https://mclo.gs/uVXxxAA)

[Repo for Axes are Weapons](https://github.com/Fourmisain/AxesAreWeapons)

[Issue posted on Axes are Weapons issue tracker](https://github.com/Fourmisain/AxesAreWeapons/issues/19)

**Comment by Fourmisain** [comment]
It's because Quill's `DiggerItemMixin` [overwrites the `hurtEnemy` method](https://github.com/Jusey1/SaljuQuill/blob/1ce3fc01e1b3100f2a12bc2f43b073facd7c2053/src/main/java/net/salju/quill/mixins/DiggerItemMixin.java#L28-L32) (to reduce all durability loss to 1) while Axes Are Weapons [tries to change the constant `2` within it](https://github.com/Fourmisain/AxesAreWeapons/blob/c39e932820f8eae34a5c6ac4792382eff8cbe337/common/src/main/java/io/github/fourmisain/axesareweapons/common/mixin/MiningToolItemMixin.java#L19-L23) (to reduce durability loss of axes/weapons to 1), which is not possible when the mixins have the same priority.
Changing the mixin priority is also not enough to fix this, since the constant `2` will be gone.

Since Quill's change is broader than mine, I'd just disable the mixin on my end, but that's quite inconvenient since I have a triple loader project and I'd have to duplicate the mixin to be able to use a mixin plugin on Forge.

Easiest fix would be to replace Quill's method overwrite with a targeted change e.g. using a [MixinExtras](https://github.com/LlamaLad7/MixinExtras) `@ModifyExpressionValue`, or an equally good `@ModifyArg` like:
 
```
	@ModifyArg(method = "postHit", at = @At(value = "INVOKE", target = "Lnet/minecraft/item/ItemStack;damage(ILnet/minecraft/entity/LivingEntity;Ljava/util/function/Consumer;)V"), index = 0)
	public int disableIncreasedDurabilityLoss(int original) {
		return 1;
	}
```
(with the appropriate mappings, so method `hurtEnemy` and invoke `hurtAndBreak`.)

Not sure if there's more that's confilicting, but at least it doesn't crash on load with this.

**Comment by Jusey1** [comment]
> It's because Quill's `DiggerItemMixin` [overwrites the `hurtEnemy` method](https://github.com/Jusey1/SaljuQuill/blob/1ce3fc01e1b3100f2a12bc2f43b073facd7c2053/src/main/java/net/salju/quill/mixins/DiggerItemMixin.java#L28-L32) (to reduce all durability loss to 1)

Ye'h, I really need to go through all of my Mixins and adjust Overwrites since they can cause conflicts like this, I am also not the best with Mixins to be honest either. At least in calling them properly or replacing a value.

**Comment by Fourmisain** [comment]
Yeah, Mixins take time to learn, especially what's best for mod compatibility, as it's not always easy to test either.
Overwrites and `@Redirect`s are generally the bane of compatibility as only one mod can use them at a time.
Same goes for `@ModifyConstant`s (surprisingly) and `cancellable` `@Inject`s - at least if they _always_ cancel. (Canceling essentially means it inserts a `return`, which will also silently skip other mod's code - which arguably worse than the game crashing on load.)

I highly recommend looking into [MixinExtras](https://github.com/LlamaLad7/MixinExtras) as it adds new injectors which are extremely helpful to avoid compatibility issues like the above, as they can all chain together if multiple mods are using them.
E.g. you can use `@WrapOperation` in place of `@Redirect`, `@ModifyExpressionValue` in place of `@ModifyConstant` (and more), and `@ModifyReturnValue` in place of cancellable injects which just want to change the return value of a method.
MixinExtras is so good, you could call it Mixin2. Fabric and NeoForge both adopted it into their loader. For regular Forge you can still use it by including it in your project.

If you wanna learn more, I can also recommend lurking in the SpongePowered and Fabric discord's mixin channels. I learned a lot just reading what people (especially LlamaLad7) are saying there.

(yap session over)

**Comment by Jusey1** [comment]
I am honestly gonna remove the DiggerItemMixin altogether on my side since it's just two small things (one being creative mode only even, the other is the durability change causing this crash). The main stuff for the axes will be left alone though in the normal AxeItemMixin however.
